/* Tremors: Perfection — static game data compiled from the design conversation. */

const _valleyBoard =
  typeof VALLEY_BOARD !== "undefined"
    ? VALLEY_BOARD
    : require("./valley-board.js").VALLEY_BOARD;

const TREMORS_DATA = {
  calamityRounds: [4, 7, 10, 12, 14],
  maxRound: 14,
  evacuateFromRound: 10,
  startingRescueTokens: 4,
  startingMedicalKits: 3,
  startingNoiseLimit: 6,
  huntSurface: 2,

  noiseBands: [
    { id: "quiet", min: 0, max: 8, label: "Quiet" },
    { id: "disturbed", min: 9, max: 14, label: "Disturbed" },
    { id: "frenzy", min: 15, max: 99, label: "Frenzy" },
  ],

  responseTable: [
    { min: 0, max: 8, id: "quiet", label: "Quiet", effect: "No extra Graboid response." },
    { min: 9, max: 11, id: "movement", label: "Movement", effect: "Graboids move toward prey / loudest noise." },
    { min: 12, max: 14, id: "hunting", label: "Hunting", effect: "Graboids move and gain +1 Hunt." },
    { min: 15, max: 19, id: "frenzy", label: "Feeding Frenzy", effect: "Graboids activate twice or a new one enters." },
    { min: 20, max: 99, id: "stampede", label: "Stampede", effect: "A new Graboid enters and all hunt aggressively." },
  ],

  items: [
    { id: "cans", name: "Tin Cans", copies: 2, text: "Throw +2 Noise onto an adjacent node. Cheap diversion." },
    { id: "line", name: "Fishing Line", copies: 2, text: "Reveal every Graboid in your sector (Hunt, surface, node)." },
    { id: "pipe", name: "Pipe", copies: 2, text: "The next Fight this game gets +1 Combat." },
    { id: "powder", name: "Black Powder", copies: 2, text: "The next Fight gets +2 Combat. Using it is +2 Noise now." },
    { id: "fuel_can", name: "Fuel Can", copies: 2, text: "Add 1 Fuel to the shared pool." },
    { id: "rope", name: "Rope", copies: 2, text: "Pull a Pinned or Threatened teammate at this node or adjacent one space clear." },
    { id: "parts", name: "Radio Parts", copies: 2, text: "+1 Work on the radio or loader objective at this node." },
    { id: "walkies", name: "Walkie-Talkies", copies: 2, text: "The next character in turn order gains +1 action this round." },
  ],

  rigs: [
    { id: "pipe_bomb", name: "Pipe Bomb", parts: ["pipe", "powder"], text: "1 wound on a surfaced Graboid here or adjacent. No fight roll. +4 Noise." },
    { id: "tripwire", name: "Tripwire Bait", parts: ["cans", "line"], text: "The next Graboid surfaces at a node you choose, with no ambush." },
    { id: "fire_bomb", name: "Fire Bomb", parts: ["fuel_can", "powder"], text: "Force a surfaced Graboid here to dive at Hunt 1. +5 Noise." },
    { id: "line_rescue", name: "Line Rescue", parts: ["rope", "walkies"], text: "Pull a Grabbed or Threatened teammate from an adjacent node onto yours." },
    { id: "field_gen", name: "Field Generator", parts: ["parts", "fuel_can"], text: "Clear Power Failure and Darkness. Dump 2 lingering noise here." },
  ],

  /* 32-node Perfection Valley board — generated in js/valley-board.js from scripts/valley_network.py */
  streets: _valleyBoard.streets,
  nodes: _valleyBoard.nodes,
  solidRockNodes: _valleyBoard.solidRockNodes,
  routes: _valleyBoard.routes,
  sectors: _valleyBoard.sectors,

  equipment: [
    { id: "rifle", name: "Rifle", kind: "weapon", heavy: true, text: "Fight with Combat +1. Heavy: +2 Noise." },
    { id: "shotgun", name: "Shotgun", kind: "weapon", heavy: true, text: "Fight at the same node with Combat +2. Heavy: +2 Noise." },
    { id: "explosives", name: "Explosives", kind: "weapon", heavy: true, text: "Can wound a surfaced Graboid. +5 Noise spike." },
    { id: "ammo", name: "Ammunition", kind: "supply", heavy: false, text: "Reroll one Fight per game." },
    { id: "binoculars", name: "Binoculars", kind: "tool", heavy: false, text: "Reveal Hunt level of Graboids in adjacent sectors." },
    { id: "improvised", name: "Improvised Weapon", kind: "weapon", heavy: false, text: "Anyone can Fight. No Combat bonus." },
  ],

  characters: [
    {
      id: "burt",
      name: "Burt Gummer",
      role: "Heavy weapons / defence / preparation",
      quote: "Broke into the wrong goddamn rec room, didn't you, you bastard!",
      movement: 2,
      nerve: 4,
      search: 3,
      combat: 5,
      start: "burt",
      color: "#7a1f1f",
      weakness: "Heavy Equipment: +1 Noise when using equipment.",
      abilities: [
        { id: "prepared", name: "Prepared for Anything", text: "Once per round, spend equipment to cancel an incoming attack or breach at your node." },
        { id: "big_guns", name: "Big Guns", text: "May use heavy weapons. Heavy weapon Fight: extra +2 Noise." },
      ],
      signature: { id: "gun_collection", name: "You Should Have Seen My Gun Collection", text: "Fight a surfaced Graboid with Combat +3 and no ammo cost. +5 Noise." },
      injuredText: "Heavy equipment is harder to haul. Fight at -1.",
    },
    {
      id: "val",
      name: "Val McKee",
      role: "Scout / movement / improvisation",
      quote: "I think we should all get the hell out while the getting's good.",
      movement: 4,
      nerve: 3,
      search: 3,
      combat: 3,
      start: "store",
      color: "#c9a227",
      weakness: "Fragile under pressure. Critical after a second serious hit.",
      abilities: [
        { id: "fast", name: "Fast", text: "Move actions may take +1 space for +1 Noise." },
        { id: "luck", name: "Val's Luck", text: "Once per round, reroll a failed test. If the reroll fails: +1 Noise." },
        { id: "dont_wait", name: "Don't Wait Around", text: "If you start a turn in an unsafe or threatened node, +1 Movement." },
      ],
      signature: { id: "run", name: "Run!", text: "Move up to 4 nodes immediately, ignoring extra terrain cost. Become Shaken." },
      injuredText: "Loses 1 Movement.",
    },
    {
      id: "earl",
      name: "Earl Bassett",
      role: "Teamwork / resilience / rescue",
      quote: "Running's not a plan. Running is what you do when the plan fails.",
      movement: 3,
      nerve: 5,
      search: 2,
      combat: 3,
      start: "store",
      color: "#2f6b4f",
      weakness: "Low specialist ability. Needs the others nearby to shine.",
      abilities: [
        { id: "knows_when", name: "Earl Knows When to Run", text: "Once per round, after another player makes Noise, move 1 node toward them for free." },
        { id: "keep_moving", name: "Keep Moving", text: "Spend an action to remove Shaken from another character at your node." },
        { id: "together", name: "We're Going Together", text: "Sharing a node: both gain +1 Nerve. If one is Injured, Earl becomes Shaken." },
      ],
      signature: { id: "get_out", name: "Let's Get the Hell Out of Here", text: "All characters at Earl's node may move 1 node with no extra Noise." },
      injuredText: "Cannot assist two characters in one turn.",
    },
    {
      id: "rhonda",
      name: "Rhonda LeBeck",
      role: "Intelligence / prediction / Graboid specialist",
      quote: "They can sense the slightest vibration through the ground. That's how they see! That's how they hunt!",
      movement: 3,
      nerve: 3,
      search: 5,
      combat: 2,
      start: "rhonda",
      color: "#3d5a80",
      weakness: "Combat 2. She is not here to shoot Graboids.",
      abilities: [
        { id: "seismologist", name: "Seismologist", text: "When a Noise threshold is reached, look at the next Calamity and keep it or bury it." },
        { id: "know_where", name: "I Know Where It Is", text: "If a Tremor is at your node or sector, spend an action to reveal a Graboid there." },
        { id: "dont_move", name: "Don't Move", text: "If you took no Move this turn, your next action this turn is 0 Noise." },
      ],
      signature: { id: "under_us", name: "They're Under Us", text: "Reveal all Graboids and Tremors in your sector. Move one underground Graboid to an adjacent sector." },
      injuredText: "Seismologist may not bury cards.",
    },
  ],

  objectives: {
    essential: [
      {
        id: "road_blocked",
        name: "The Road Is Blocked",
        location: "highway",
        work: 2,
        noise: 1,
        flavour: "Investigate the landslide. Perfection is not getting out the easy way.",
        pass: "Reveal the blocked highway and unlock Find Another Way Out as known. Gain Alternative Route intel.",
        fail: "Permanent Danger Zone on the highway. Graboid Aggression +1.",
      },
      {
        id: "radio_working",
        name: "Get the Radio Working",
        location: "radio",
        work: 2,
        noise: 2,
        flavour: "The phone line to Bixby is dead. Splice it, or boost Walter's CB from the poles. Either way it makes a racket.",
        pass: "Gain 1 Rescue token.",
        fail: "No outside help. Desperation +1 now, and +1 every 2 rounds.",
      },
      {
        id: "seismograph",
        name: "Find Rhonda's Seismograph",
        location: "rhonda",
        work: 2,
        noise: 0,
        flavour: "Horse Path 2 — the readings are wrong for earthquakes. That is the point.",
        pass: "Learn a Graboid rule: they always investigate the greatest noise in their sector.",
        fail: "Blind Hunting: surfaced Graboids pick randomly among noisy nodes.",
      },
      {
        id: "heavy_vehicle",
        name: "Secure a Heavy Vehicle",
        location: "caterpillar",
        work: 2,
        noise: 3,
        flavour: "The Caterpillar is the only thing in town that weighs enough to matter.",
        pass: "Loader ready for the valley.",
        fail: "Loader starts damaged. Repair still required to leave.",
      },
      {
        id: "safe_ground",
        name: "Find the Safe Ground",
        location: "workshop",
        work: 2,
        noise: 0,
        flavour: "Dig through the dump to the old mining company foundations. Concrete and rock — Graboids cannot get purchase.",
        pass: "Boulder paths, towers, and the junkyard foundations count as Solid Rock (Graboids cannot surface there).",
        fail: "Safe terrain stays hidden until someone stands on it.",
      },
      {
        id: "meeting_point",
        name: "Get Everyone to the Meeting Point",
        location: "store",
        work: 2,
        noise: 1,
        flavour: "If you split up forever, you die separately.",
        pass: "Chang's Market becomes the Assembly Point. Starting together later is easier.",
        fail: "Survivors will scatter if you are forced out.",
      },
    ],
    optional: [
      {
        id: "walters_store",
        name: "Raid Chang's Market",
        location: "store",
        work: 1,
        noise: 1,
        flavour: "Ammunition to antibiotics, Walter stocks it all. For now.",
        pass: "Gain 2 Supply cards (Medical Kit and Distraction).",
        fail: "Place Looted. No further supplies here.",
      },
      {
        id: "burts_arsenal",
        name: "Burt's Arsenal",
        location: "burt",
        work: 1,
        noise: 4,
        flavour: "The basement is a museum of poor impulse control.",
        pass: "Gain Explosives and Ammunition.",
        fail: "Burt will not leave without his equipment. He is stuck here until this is done or abandoned.",
      },
      {
        id: "gather_fuel",
        name: "Gather Fuel",
        location: "fuel",
        work: 1,
        noise: 2,
        flavour: "Without fuel, the loader is a very expensive rock.",
        pass: "Gain 3 Fuel. Vehicle movement is available.",
        fail: "All vehicle / metal movement +1 Noise.",
      },
      {
        id: "medical",
        name: "Recover the Medical Supplies",
        location: "clinic",
        work: 1,
        noise: 1,
        flavour: "Jim kept a kit. You are going to need it.",
        pass: "Gain 2 Medical Kits.",
        fail: "Draw Injury: the next Knockdown on anyone is one step worse.",
      },
      {
        id: "horses",
        name: "Save the Horses",
        location: "school",
        work: 1,
        noise: 1,
        flavour: "Horse Path 1 — the corral horses are quieter than any truck, until they spook.",
        pass: "Gain 2 Quiet Movement tokens (a Move with 0 Noise).",
        fail: "Horses are gone.",
      },
      {
        id: "trailer_salvage",
        name: "Salvage the Trailer",
        location: "trailer",
        work: 1,
        noise: 2,
        flavour: "Nestor's tin can might still hitch to the loader.",
        pass: "People Carrier: the loader can take everyone.",
        fail: "Loader carries only 2 survivors at a time.",
      },
      {
        id: "basement",
        name: "The Basement",
        location: "burt",
        work: 2,
        noise: 2,
        flavour: "Enclosed, valuable, and a dinner bell if you linger.",
        pass: "Gain a powerful equipment piece (Explosives if missing, else Rifle).",
        fail: "Graboid breaches the building. Location becomes inaccessible.",
      },
    ],
    character: [
      {
        id: "char_burt",
        name: "Burt — Prepared",
        character: "burt",
        location: "burt",
        work: 1,
        noise: 4,
        flavour: "Recover the ammunition and weapon stores.",
        pass: "Arsenal card: Burt may Fight once per round without spending an action's extra noise beyond the gun itself.",
        fail: "Burt keeps only his personal weapon.",
      },
      {
        id: "char_rhonda",
        name: "Rhonda — Something Doesn't Add Up",
        character: "rhonda",
        location: "rhonda",
        work: 1,
        noise: 0,
        flavour: "Collect enough seismic readings to pin down Graboid behaviour.",
        pass: "Reveal two hidden Graboids' Hunt levels and sectors.",
        fail: "Graboids gain Unpredictable: Hunt checks sometimes skip a step.",
      },
      {
        id: "char_val_earl",
        name: "Val & Earl — Don't Wait Around",
        character: "val",
        location: "bar",
        work: 1,
        noise: 1,
        flavour: "Get Melvin off the street before his next prank calls in something real.",
        pass: "Gain a Distraction token. Val and Earl may share one free Move this round.",
        fail: "Panic +1. NPCs generate +1 Noise if a Panic calamity hits.",
      },
      {
        id: "char_mindy",
        name: "Nancy — Where's Mindy?",
        character: "val",
        location: "nancy",
        work: 1,
        noise: 0,
        flavour: "Find Mindy and get her off the pogo stick.",
        pass: "Mindy is safe. Gain 1 Quiet Movement.",
        fail: "Mindy stays Exposed in town. Pogo calamities hunt her.",
      },
    ],
  },

  calamities: [
    { id: 1, act: 1, title: "THE ROAD IS BLOCKED", flavour: "A landslide has done what the Graboids couldn't: it has cut the town off from Bixby.",
      quiet: "Place a Blocked Route on the Bixby Road.", disturbed: "Block the Bixby Road and one adjacent route.", frenzy: "The Bixby Road closes. Essential: Find Another Way Out if the road objective is unfinished." },
    { id: 2, act: 1, title: "STRANGE TREMORS", flavour: "There are no earthquakes on Rhonda's readings. Whatever is moving down there isn't following the rules.",
      quiet: "Place 1 Tremor marker.", disturbed: "Place 2 Tremors.", frenzy: "Nearest Graboid moves toward the highest-noise node and gains +1 Hunt." },
    { id: 3, act: 1, title: "UNDERGROUND", flavour: "Something passes beneath the town. You don't see it. You don't need to.",
      quiet: "Place a Tremor marker.", disturbed: "Move one Graboid one sector.", frenzy: "All underground Graboids move toward the loudest sector." },
    { id: 4, act: 1, title: "THE DEAD SHEEP", flavour: "Word comes in from Old Fred's place south of town, on the Bixby road. His flock didn't wander off. Whatever did it left very little behind.",
      quiet: "Reveal a clue at the Horse Corral.", disturbed: "Remove livestock / lose Quiet Movement if you had horses.", frenzy: "Aggression +1. The horses panic: Tremor at the Horse Corral." },
    { id: 5, act: 1, title: "EDGAR'S PYLON", flavour: "They found Edgar up an electrical tower outside town, rifle in hand, dead of thirst. Whatever chased him didn't have to follow him up.",
      quiet: "Gain a Graboid behaviour clue.", disturbed: "Desperation +1.", frenzy: "Open ground beneath the Telephone Line is permanently Unsafe." },
    { id: 6, act: 1, title: "TREMOR BREACH", flavour: "The ground moves. Dirt sprays. Then the town remembers exactly what is under it.",
      quiet: "Add a Tremor marker.", disturbed: "A Graboid in the loudest sector gains +2 Hunt.", frenzy: "A Graboid surfaces at the loudest node in its sector." },
    { id: 7, act: 1, title: "THEY'RE LEARNING", flavour: "The creatures aren't just following noise anymore. They're beginning to understand the pattern.",
      quiet: "No effect.", disturbed: "Reveal one Graboid's Hunt level.", frenzy: "Adaptive: the next repeated Move style used gets +1 Noise." },
    { id: 8, act: 1, title: "THE FOUNDATION", flavour: "Being on top of something seemed like a good idea. Then the thing underneath started digging.",
      quiet: "Buildings remain safe.", disturbed: "Mark one occupied building Compromised.", frenzy: "An occupied building becomes Unsafe. Survivors there must leave next turn or be Exposed." },
    { id: 9, act: 1, title: "POWER FAILURE", flavour: "The lights flicker. Then everything goes dark. Somewhere nearby, something starts moving.",
      quiet: "Disable one powered location (Chang's or Chang's Trailer).", disturbed: "Disable Chang's, Chang's Trailer, and the Telephone Line.", frenzy: "Darkness: all actions +1 Noise until someone Works at Chang's Trailer." },
    { id: 10, act: 1, title: "THE REFRIGERATOR", flavour: "Nobody notices the refrigerator until it starts running. Suddenly that hum sounds like a dinner bell.",
      quiet: "Chang's generates +1 Noise next round.", disturbed: "Chang's generates +2 Noise next round.", frenzy: "Nearest Graboid moves toward Chang's and gains +1 Hunt." },
    { id: 11, act: 2, title: "WHERE'S MINDY?", flavour: "Someone hears music. Someone else hears a pogo stick. Everyone else hears disaster.",
      quiet: "Place Mindy at Nancy's House.", disturbed: "Mindy moves toward open ground (the Horse Corral).", frenzy: "Mindy is Exposed at the Horse Corral. Nearest Graboid hunts her." },
    { id: 12, act: 2, title: "THE POGO STICK", flavour: "It doesn't matter how often everyone says stop jumping.",
      quiet: "No effect.", disturbed: "+2 Noise at Mindy's location.", frenzy: "+4 Noise at Mindy and nearest Graboid moves toward her." },
    { id: 13, act: 2, title: "THE BARBED WIRE", flavour: "The corral fence has come down across the safest route through town.",
      quiet: "Hazard on Horse Corral routes.", disturbed: "Crossing the Horse Corral costs +1 extra Move point.", frenzy: "Crossing the Horse Corral: 50% chance of Injured." },
    { id: 14, act: 2, title: "CHANG'S MARKET", flavour: "The market is supposed to be where everyone gathers. That feels less reassuring.",
      quiet: "Chang's remains safe.", disturbed: "Chang's is a High-Value Noise Location (+1 to actions there).", frenzy: "Graboid under Chang's. Everyone there must flee or become Threatened." },
    { id: 15, act: 2, title: "NO SIGNAL", flavour: "The radio crackles, then nothing. Bixby is 38 miles away. It may as well be 380.",
      quiet: "No effect.", disturbed: "Radio objective needs +1 extra Work.", frenzy: "Radio objective fails unless already completed." },
    { id: 16, act: 2, title: "BURT'S ARSENAL", flavour: "Burt prepared for everything. Giant underground predator was not on the list.",
      quiet: "Burt gains a Rifle if he has none.", disturbed: "Burt gains a weapon and +2 Noise at his house.", frenzy: "Weapon cache: gain Explosives, then a Graboid response in sector C." },
    { id: 17, act: 2, title: "THE TUMBLER", flavour: "Burt's ammunition is getting polished. Heather has noticed something in the distance.",
      quiet: "No consequence.", disturbed: "Machine Running: +1 Noise at Burt's each round until someone Works to stop it.", frenzy: "A Graboid moves directly to sector C and gains +1 Hunt." },
    { id: 18, act: 2, title: "WRONG HOUSE", flavour: "The creatures don't know where everyone is hiding. They're trying buildings at random. For now.",
      quiet: "Nothing.", disturbed: "A random occupied building becomes Threatened.", frenzy: "Graboid surfaces at the most occupied building's sector, targeting that node." },
    { id: 19, act: 2, title: "THE TRAILER", flavour: "Nestor's trailer looked like shelter. The Graboids have another opinion.",
      quiet: "No effect.", disturbed: "Trailer becomes Compromised.", frenzy: "Trailer destroyed. Anyone there is Exposed and Shaken." },
    { id: 20, act: 2, title: "THE WATER TOWER", flavour: "The town suddenly has an excellent view. So does the thing underneath.",
      quiet: "Water Tower is a safe observation point.", disturbed: "Climbing it costs +1 Move.", frenzy: "Tower Compromised. Graboid +1 Hunt in sector C." },
    { id: 21, act: 2, title: "A DECOY", flavour: "Sometimes the best way to survive a Graboid is to persuade it somebody else is more interesting.",
      quiet: "Gain a Distraction token.", disturbed: "Gain a Distraction and a Tremor.", frenzy: "Redirect one Graboid, then another Graboid gains +1 Hunt." },
    { id: 22, act: 2, title: "THE DEEPENING SILENCE", flavour: "Everything goes quiet. Nobody talks. Nobody moves. Somewhere below, something waits.",
      quiet: "Remove 1 Noise from the loudest node.", disturbed: "Each character must Hide or lose their next first action.", frenzy: "Ambush: nearest hidden Graboid +2 Hunt before anyone acts." },
    { id: 23, act: 2, title: "THE GROUND GIVES WAY", flavour: "A patch of earth collapses. The town has one less piece of itself.",
      quiet: "Block a minor route (Corral–Junkyard).", disturbed: "Block Dump–Bixby Road.", frenzy: "Block Dump–Bixby Road and create a Graboid entrance in sector E." },
    { id: 24, act: 2, title: "PANIC", flavour: "Stay and hope, or run and hope. Neither sounds good.",
      quiet: "Nothing.", disturbed: "Desperation +1. Shaken on one random character.", frenzy: "All Exposed characters generate +1 Noise. Nearest Graboid activates." },
    { id: 25, act: 2, title: "THE BOMBS", flavour: "Burt doesn't call them bombs.",
      quiet: "Gain Explosives.", disturbed: "Gain Explosives and +2 Noise at Burt's.", frenzy: "Gain Explosives and trigger a Feeding Frenzy response." },
    { id: 26, act: 3, title: "BROKE INTO THE WRONG PLACE", flavour: "The creature picks the wrong building. Then everyone inside makes it regret that.",
      quiet: "If Burt is in a building, he gains Prepared.", disturbed: "Repel: Hunt -1 on a surfaced Graboid, or +1 Wound if none.", frenzy: "If Burt is present at a surfaced Graboid, he may destroy it for +3 Noise." },
    { id: 27, act: 3, title: "THEY'RE TESTING US", flavour: "First the store. Then the houses. Then the trailer. The next target won't be random.",
      quiet: "Reveal the next Calamity title.", disturbed: "Reveal next Calamity and one Graboid sector.", frenzy: "Choose: bury the next Calamity, or a Graboid surfaces at the loudest node." },
    { id: 28, act: 3, title: "THE CATERPILLAR", flavour: "Thirty tons of machinery is looking less like construction equipment and more like a lifeboat.",
      quiet: "Reveal Loader location (already known). +1 Fuel.", disturbed: "Loader requires repair: extra Work on the vehicle objective.", frenzy: "Loader damaged. Metal movement +2 Noise until repaired." },
    { id: 29, act: 3, title: "NO WAY BACK", flavour: "Perfection was never easy to leave. Now the town is refusing to let anyone go.",
      quiet: "Block one remaining Bixby Road route.", disturbed: "Block two south routes.", frenzy: "All unfinished Essential objectives become Urgent (must complete this round or fail)." },
    { id: 30, act: 3, title: "GET OUT OF PERFECTION", flavour: "There comes a point where staying isn't brave anymore. It's just stupid.",
      quiet: "Final warning. One round remains after this.", disturbed: "Evacuation begins. Unfinished optional objectives are abandoned.", frenzy: "PERFECTION FALLS. Unfinished Essentials fail. Resolve the end of Phase 1 now." },
  ],
};

if (typeof module !== "undefined") {
  module.exports = { TREMORS_DATA };
}
